### PR TITLE
Added Redis Cache Provier (with unit tests) using StackExchange or ServiceStack and changed get methods from object to generic

### PR DESCRIPTION
**Pull request by imperugo**
Hi,
here there is Redis implementation (it works, just need to create the package for nuget). Moreover I changed _apicache_get call to _apicache.get<T> (should be better than a cast)

### CODE REVIEW

**Comment by filipw** [comment]
Thenks! the only problem is ServiceStack.Redis is AGPL license. You should downgrade to version 3.9.71 which was the last truly free one or switch to StackExchange.

**Comment by drewfreyling** [comment]
Or https://github.com/NServiceKit/NServiceKit

**Comment by imperugo** [comment]
Reverted to 3.9.71

**Comment by imperugo** [comment]
Pushed also StackExchange.Redis with tests

**Comment by imperugo** [comment]
it's old, must be updated.
I'll open another one as soon as I can

**Pull request closed without merging**
