### PR TITLE
Cache Key generation enhancements

### PR DESCRIPTION
**Pull request by dmalanij**
This PR includes: 
* a small refactor on the `DefaultCacheKeyGenerator` to encapsulate some of the internal logic into protected methods for better extensibility
* a new `PerUserCacheKeyGenerator` that derives from the default one but includes user identity as one fragment of the key. This tackles request in #163. 
* Unit tests for both implementations of the `ICacheKeyGenerator`

The main driver is the second point, I believe is a very common scenario for any API that filters information based on user profile and better to provide it already in the package. Maybe we can also discuss other implementations to cover common scenarios similar to what's requested in #159.

Cheers!

### CODE REVIEW

**Comment by filipw** [comment]
Sorry for the delay - great PR - thanks a lot. Will release it this week 👍

**Comment by dmalanij** [comment]
You're welcome!

**Comment by GithubMaastricht** [comment]
Dear readers, how to enable or use "PerUserCacheKeyGenerator" ?

**1)** I have implemented 

public class PerUserCacheKeyGenerator : DefaultCacheKeyGenerator   
{      public override string MakeCacheKey
       { .....

**2)** and decorated the Controllers with:
[CacheOutput(ClientTimeSpan = 259200, ServerTimeSpan = 259200, CacheKeyGenerator = typeof(PerUserCacheKeyGenerator))]

**3)** and registered the PerUserCacheKeyGenerator class in WebApiConfig.cs with:

config.CacheOutputConfiguration().RegisterCacheOutputProvider(() => new MemoryCacheDefault());
config.CacheOutputConfiguration().RegisterDefaultCacheKeyGeneratorProvider(() => new PerUserCacheKeyGenerator());


But still the class PerUserCacheKeyGenerator  is not used when requesting the controllers actions....

Any help?

**Comment by nomorechickennuggets** [comment]
cc @dmalanij - I have the same q as @GithubMaastricht ^^

**Comment by dmalanij** [comment]
I'm really sorry, don't know what happened back in 2019 that I've never replied to @GithubMaastricht 

@mickproj, do you have a code sample to take a look to? 

I took me a while to get this back (my lord, my PR is 5 years old and the whole project is much older, had to travel back in time to remember how to do stuff like in _those ages_), but just changing one of the controllers in the provided demo project to use the `PerUserCacheKeyGenerator` worked as expected. 

Basically I've modified Teams2Controller.cs, line 19 so it looks like this

```cs
        [CacheOutput(ClientTimeSpan = 50, ServerTimeSpan = 50, CacheKeyGenerator = typeof(PerUserCacheKeyGenerator))]
        public IEnumerable<Team> Get()
        {
            return Teams;
        }
```

After that, requesting `http://localhost:999/api/teams2` triggers the logic in the `PerUserCacheKeyGenerator` (you can check it with the debugger or adding log). 


Besides that, I should check but I'm quite sure that some time after applying the MR, @filipw published a new version of the nuget package including it, so there's no need to reimplement the class (unless you'd like to change its behavior, which you can do by inheriting from it and overriding some of the methods)

**Comment by dmalanij** [comment]
Oh dear... been working on the unrelated issue about updating the solution in general and I think there's a something odd in how [registrations are being handled](https://github.com/filipw/Strathweb.CacheOutput/blob/dev/src/WebApi.OutputCache.V2/CacheOutputConfiguration.cs#L28)

Basically if there are several calls to `RegisterDefaultCacheKeyGeneratorProvider` due to the inner implemation with GetOrAdd, only first invocation is going to be registered.

I need to make my mind around this but looks as a bug given [there is a test](https://github.com/filipw/Strathweb.CacheOutput/blob/dev/test/WebApi.OutputCache.V2.Tests/CacheKeyGeneratorRegistrationTests.cs#L58) stating the opposite. Thing is... test goes green due to weird stuff:

- first of all, nunit 2 is not handling well the `Assert.Fail` (even if it gets executed, test is not breaking)
- then, the mock has no expectations (no verifiable setup) so `VerifyAll()` is ok

I was going crazy with the test going red with the nunit update and after some time I've unravelled this. I'll continue with that work but just to let you know that if using the Register, that might be causing the odd behaviour.

**Comment by nomorechickennuggets** [comment]
just wanted to hop in and thank you @dmalanij for this help + the wonderful PRs (and @filipw for the wonderful library) - took me a while to try it but the attribute approach works perfectly out of the box. Appreciate you 🙏

**Comment by dmalanij** [comment]
Thanks @mickproj for your kind words.

I'm going to spend some time trying to update this in general, but is being like a side free time project so can't promise any deadline. Anyway, the owner here is still @filipw, so he'll decide what goes next in term of the roadmap.

**Pull request merged**
